POST http://localhost:8080/events
content-type: application/json

{
  "name": "Another Test event",
  "description": "Another test event",
  "location": "Another test location",
  "dateTime": "2026-01-01T15:30:00.000Z"
}